### ISSUE TITLE
Importing animations - <<RenderSettings.fps expects int type, not float>>

### ISSUE THREAD

**Issue by AlyMar1994** [andrewfullard/Blender-ALAMO-Plugin#9]
CONTEXT: I'm sorry if this isn't the right place for it -- Rhino pointed me here to get an updated version of the ALAMO Plugin since Gaukler/AlamoEngine-Tools' mirror causes skeleton issues on import with a bunch of models, but we were both stumped on the error I got when importing FoC models, and suggested I make a report.  I am somewhat Blender illiterate.

PROBLEM: When importing any FoC model (or an EaW model with converted animations), the animations fail to import.  Popup and console screenshots are provided below.  Animations can "play" in the timeline, but they don't export and don't visibly play.  The errors occur on all FoC models with animations I import.  Screenshots below are done trying to import "W_GRENADE.ALO"

----

OS: Windows 11
GPU: AMD RX 6700 XT
CPU: Intel i9-11900KF 3.5GHz
Blender Version: 3.6 (Stable - LT) (Tested on 3.3, same results)
ALAMO Plugin Version: Latest (Cloned from Repo, NOT using Release 0.0.3.5)

----

If there's any other form of logging/console messages you need I am 100% willing to provide them if it means I finally can use a functional Blender plugin.  If this wasn't enough let me know.

**Screenshots:**
![Popup Error](https://github.com/user-attachments/assets/2c05bd6e-244c-4317-868a-92a0063a19dd)
![Console](https://github.com/user-attachments/assets/f66b9b69-4bc7-45be-8bae-23cb61acc59a)

**Comment by andrewfullard** [comment]
Outdated version, see latest https://github.com/andrewfullard/Blender-ALAMO-Plugin/blob/master/io_alamo_tools/import_ala.py#L284
